/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Refactored to TypeScript with extracted material logic.
*/

import { useGLTF } from '@react-three/drei'
import type { Mesh } from 'three'
import type { GlazePart } from '../types'
import { useModelMaterials } from '../hooks/useModelMaterials'

const MODEL_PATH = './models/Cup.gltf'

interface CupProps {
  clay: string
  glaze: string
  glazePart: GlazePart
}

export function Cup({ clay, glaze, glazePart }: CupProps) {
  const { nodes, materials } = useGLTF(MODEL_PATH)
  const { getMaterial, clayMaterial } = useModelMaterials({ clay, glaze, glazePart, materials })

  // Cast nodes to Mesh so TypeScript recognises `.geometry`
  const n = nodes as Record<string, Mesh>

  // Map each glazePart value to a boolean flag per mesh section:
  // [inner, top, middle, bottom]
  const glazeMap: Record<GlazePart, [boolean, boolean, boolean, boolean]> = {
    'Completely glazed':  [true,  true,  true,  true],
    'Half glazed':        [true,  true,  true,  false],
    'Only glazed inside': [true,  false, false, false],
    'No glaze selected':  [false, false, false, false],
  }

  const [inner, top, middle, bottom] = glazeMap[glazePart] ?? [false, false, false, false]

  return (
    <group dispose={null}>
      <mesh geometry={n.CupBase.geometry}   material={clayMaterial} />
      <mesh geometry={n.CupInner.geometry}  material={getMaterial(inner)} />
      <mesh geometry={n.CupTop.geometry}    material={getMaterial(top)} />
      <mesh geometry={n.CupMiddle.geometry} material={getMaterial(middle)} />
      <mesh geometry={n.CupBottom.geometry} material={getMaterial(bottom)} />
    </group>
  )
}

useGLTF.preload(MODEL_PATH)
